trigger:
- main  # Ajusta esto a la rama que estés utilizando

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '14.x'
  displayName: 'Set up Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build project'

- task: CopyFiles@2
  inputs:
    contents: '**/dist/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Copy files to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/dist'
    artifactName: 'dist'
  displayName: 'Publish build artifacts'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(Build.ArtifactStagingDirectory)/dist'
    api_location: ''
    output_location: ''
    app_build_command: ''
    api_build_command: ''
    skip_app_build: true
    app_location: ''
    output_location: ''
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
  displayName: 'Deploy to Azure Static Web Apps'
